#!/bin/bash

if [[ -z $1 ]];
then
    echo "Please provide the name of the tester class"
    exit
fi

javac -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar $1.java
java -cp .:lib/junit-4.13.2.jar:lib/hamcrest-core-1.3.jar org.junit.runner.JUnitCore $1

rm *.class
